import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";

export const font_primary = Inter({
  weight: ["700"],
  subsets: ["latin"]
})


export const font_secondary = Inter({
  weight: ["500"],
  subsets: ["latin"]
})

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={font_primary.className}
      >

    <h1 className="flex justify-center items-center mt-[1rem] text-[1.25rem]">ovapp</h1>
        {children}
      </body>
    </html>
  );
}
